// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyHuTc3UZGxfEfmGa3se4uYxgMFGgZCo',
    appId: '1:906512269675:web:63c77af43030e1c1becc2e',
    messagingSenderId: '906512269675',
    projectId: 'laweh-da92d',
    authDomain: 'laweh-da92d.firebaseapp.com',
    storageBucket: 'laweh-da92d.appspot.com', 
    measurementId: 'G-RG2D0LJMW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZcpeFQFJmCK2powA8SubU5B7FWJexGM',
    appId: '1:906512269675:android:ba1df08fc949a1c5becc2e',
    messagingSenderId: '906512269675',
    projectId: 'laweh-da92d',
    storageBucket: 'laweh-da92d.appspot.com', 
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eetqGlQjhKvY2JIngRONE8fqmydjvLY',
    appId: '1:906512269675:ios:077f52ef236f4360becc2e',
    messagingSenderId: '906512269675',
    projectId: 'laweh-da92d',
    storageBucket: 'laweh-da92d.appspot.com',
    iosBundleId: 'com.example.laweh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3eetqGlQjhKvY2JIngRONE8fqmydjvLY',
    appId: '1:906512269675:ios:077f52ef236f4360becc2e',
    messagingSenderId: '906512269675',
    projectId: 'laweh-da92d',
    storageBucket: 'laweh-da92d.appspot.com',
    iosBundleId: 'com.example.laweh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoyHuTc3UZGxfEfmGa3se4uYxgMFGgZCo',
    appId: '1:906512269675:web:b499799d78c32f91becc2e',
    messagingSenderId: '906512269675',
    projectId: 'laweh-da92d',
    authDomain: 'laweh-da92d.firebaseapp.com',
    storageBucket: 'laweh-da92d.appspot.com',
    measurementId: 'G-154K23LX76',
  );
}
